# Frontend Dockerfile for development
FROM node:20-slim

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"


WORKDIR /app/web-frontend

RUN corepack enable

RUN mkdir -p /app/web-frontend && chown -R node:node /app

USER node

COPY --chown=node:node web-frontend/package.json web-frontend/pnpm-lock.yaml* ./

RUN pnpm install --ignore-scripts

EXPOSE 5173

CMD ["pnpm", "dev", "--host", "0.0.0.0"]
