
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev.backend
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./backend:/app/backend
      - ./3rd_party:/app/3rd_party
      - ./web-frontend:/app/web-frontend

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev.frontend
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - "5173:5173"
    volumes:
      - ./web-frontend:/app/web-frontend
      - frontend_node_modules:/app/web-frontend/node_modules
    depends_on:
      - backend
    environment:
      - CI=true

volumes:
  frontend_node_modules:
