# Frontend Dockerfile for development
FROM node:20-slim

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"


WORKDIR /app/web-frontend

RUN corepack enable

COPY web-frontend/package.json web-frontend/pnpm-lock.yaml* ./

RUN pnpm install

EXPOSE 5173

CMD ["pnpm", "dev", "--host", "0.0.0.0"]
