#![recursion_limit = "10000"]
pub mod ast_annotation;
pub mod ast_runner;
pub mod codegen;
pub mod ir;
pub mod ir2;
pub mod parser;
pub mod source_annotation;
pub mod sources;
pub mod tokenizer;
pub mod type_check;
pub mod ucodegen;
pub mod wasm_api;
